name: ilspy # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: ILSpy is the open-source .NET assembly browser and decompiler.- # 79 char long summary
description: |
  Features

    Decompilation to C#
    Whole-project decompilation (csproj, not sln!)
    Search for types/methods/properties (substring)
    Hyperlink-based type/method/property navigation
    Base/Derived types navigation, history
    BAML to XAML decompiler
    Extensible via plugins (MEF)
    Check out the language support status

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  ilspy:
    command: ./ILSpy
    plugs:
      - home
parts:
  ilspy:
    plugin: dotnet
    dotnet-version: 5.0
    dotnet-runtime-version: '5.0.3'
    source: .
    override-build: |
      cd ILSpy
      dotnet build -c Release
      dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=false --self-contained true -o $SNAPCRAFT_PART_INSTALL
      chmod 0755 $SNAPCRAFT_PART_INSTALL/ILSpy
    stage-packages: 
      - libgtk-3-0 #For Avalonia
      - fontconfig 
